services:
  - type: web
    name: maintenance-app
    env: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_PATH
        value: /tmp/maintenance.db
    healthCheckPath: /static/index.html
